# Generated by Django 3.2.9 on 2021-11-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211116_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
