# Generated by Django 3.2.9 on 2021-11-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211130_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponCode',
        ),
    ]
